group 'com.ha.nep.haudiotagger_fingerprint'
version '1.0-SNAPSHOT'

apply plugin: 'com.android.library'

android {
    namespace 'com.ha.nep.haudiotagger_fingerprint'
    compileSdkVersion 37

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        main.jniLibs.srcDirs = ['src/main/jniLibs']
    }

    defaultConfig {
        minSdkVersion 24
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}

kotlin {
    jvmToolchain(17)
}
