// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cancel_flag`, `decode_to_pcm`, `fingerprint_inner`, `fingerprint_pcm`, `is_cancelled`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Compute the fingerprint of the audio file at `path`.
///
/// Decodes the full audio stream (MP3, FLAC, Ogg Vorbis, WAV, AIFF,
/// M4A/AAC/ALAC) and fingerprints the PCM content. Tags, filenames, and
/// container differences do not affect the result.
///
/// Async without touching FRB's worker pool (whose web bootstrap hardcodes
/// the `wasm_bindgen` JS global): native runs on tokio background threads,
/// web cooperatively yields between decode chunks on the main thread.
/// Pass `cancel_id` from [`cancellation_token_new`] to abort long scans.
Future<AudioFingerprint> fingerprint(
        {required String path, BigInt? cancelId}) =>
    RustLib.instance.api
        .crateApiFingerprintFingerprint(path: path, cancelId: cancelId);

/// Compute the fingerprint of in-memory audio `bytes` (for web/WASM).
///
/// Async, same execution model as [`fingerprint`]. Pass `cancel_id` from
/// [`cancellation_token_new`] to abort long scans.
Future<AudioFingerprint> fingerprintFromBytes(
        {required List<int> bytes, BigInt? cancelId}) =>
    RustLib.instance.api.crateApiFingerprintFingerprintFromBytes(
        bytes: bytes, cancelId: cancelId);

/// Compare two fingerprints, returning a similarity score from `0.0` to `1.0`.
///
/// `1.0` means (near-)identical audio. Copies and renames score `1.0`;
/// different encodings of the same recording typically score above `0.8`;
/// unrelated audio scores near `0.0`.
double similarity({required AudioFingerprint a, required AudioFingerprint b}) =>
    RustLib.instance.api.crateApiFingerprintSimilarity(a: a, b: b);

/// Create a cancellation token, returned as an id for Dart's
/// `CancellationToken`. Pass it as `cancel_id` to abort long scans.
BigInt cancellationTokenNew() =>
    RustLib.instance.api.crateApiFingerprintCancellationTokenNew();

/// Trip a token created by [`cancellation_token_new`]. In-flight fingerprint
/// calls observing it abort with [`FingerprintError::Cancelled`]. Idempotent.
void cancellationTokenCancel({required BigInt id}) =>
    RustLib.instance.api.crateApiFingerprintCancellationTokenCancel(id: id);

/// Release a token id. Ids are reusable resources owned by the caller:
void cancellationTokenFree({required BigInt id}) =>
    RustLib.instance.api.crateApiFingerprintCancellationTokenFree(id: id);

/// A perceptual audio fingerprint.
///
/// Two recordings of the same audio produce equal (or near-equal)
/// fingerprints even if filenames, tags, containers, or encoders differ.
/// Compare with [`similarity`].
class AudioFingerprint {
  /// Raw Chromaprint items (one `u32` per ~0.12s of audio).
  final Uint32List values;

  /// Decoded audio duration in whole seconds.
  final int durationSecs;

  const AudioFingerprint({
    required this.values,
    required this.durationSecs,
  });

  @override
  int get hashCode => values.hashCode ^ durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioFingerprint &&
          runtimeType == other.runtimeType &&
          values == other.values &&
          durationSecs == other.durationSecs;
}
