// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_to_pcm`, `fingerprint_pcm`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Compute the fingerprint of the audio file at `path`.
///
/// Decodes the full audio stream (MP3, FLAC, Ogg Vorbis, WAV, AIFF,
/// M4A/AAC/ALAC) and fingerprints the PCM content. Tags, filenames, and
/// container differences do not affect the result.
Future<AudioFingerprint> fingerprint({required String path}) =>
    RustLib.instance.api.crateApiFingerprintFingerprint(path: path);

/// Compute the fingerprint of in-memory audio `bytes` (for web/WASM).
Future<AudioFingerprint> fingerprintFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiFingerprintFingerprintFromBytes(bytes: bytes);

/// Compare two fingerprints, returning a similarity score from `0.0` to `1.0`.
///
/// `1.0` means (near-)identical audio. Copies and renames score `1.0`;
/// different encodings of the same recording typically score above `0.8`;
/// unrelated audio scores near `0.0`.
Future<double> similarity({
  required AudioFingerprint a,
  required AudioFingerprint b,
}) =>
    RustLib.instance.api.crateApiFingerprintSimilarity(a: a, b: b);

/// A perceptual audio fingerprint.
///
/// Two recordings of the same audio produce equal (or near-equal)
/// fingerprints even if filenames, tags, containers, or encoders differ.
/// Compare with [`similarity`].
class AudioFingerprint {
  /// Raw Chromaprint items (one `u32` per ~0.12s of audio).
  final Uint32List values;

  /// Decoded audio duration in whole seconds.
  final int durationSecs;

  const AudioFingerprint({required this.values, required this.durationSecs});

  @override
  int get hashCode => values.hashCode ^ durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioFingerprint &&
          runtimeType == other.runtimeType &&
          values == other.values &&
          durationSecs == other.durationSecs;
}
